### ISSUE TITLE
balanced_loss file is missing

### ISSUE THREAD

**Issue by prakashchhipa** [faixan-khan/FishNet#3]
Line no 406 in main_v2.py - from balanced_loss import Loss - balanced_loss.py is missing. Please provide it.

**Comment by floppycracken** [comment]
Hello,
Thank you for pointing this out. I will have a look and soon upload whatever code is missing.

**Comment by lx709** [comment]
balanced_loss is a Python library. Check it at https://pypi.org/project/balanced-loss/
